name: Deploy Theme

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: forge
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/forge/FT && git pull origin master
            rsync -av --delete --exclude='.git' /home/forge/FT/federalist-times-theme/ /home/forge/federalisttimes.com/public/wp-content/themes/federalist-times-theme/
